### PR TITLE
B 4.2 texture transform bind preview

### PR DESCRIPTION
**Pull request by tdw46**
Added preview for vrm1 texture transform binds.

Texture Transform Bind Preview

### CODE REVIEW

**Comment by tdw46** [comment]
Just realized I might want to make this loop through all expressions and texture transforms binds instead of just working for the active bind. I'll commit an update with that in a little bit.

**Comment by tdw46** [comment]
Ahh, I see I need to fix some type annotations. Will do, haven't done much of that before, but this is a good chance to practice.

Also, I noticed some more issues in testing. Will ping you when all looks good.

**Comment by tdw46** [comment]
@saturday06 I think this is good to merge, thanks for your patience! Let me know if there are any parts of the code you'd like formatted differently. I'm trying to learn the best practices you follow.

**Comment by tdw46** [comment]
FYI, I haven't done the logic for the override blink, look, mouth features in the texture bind previews. But I figure that can come in a later update. Also haven't tested UV vertex offset masking based on material for objects with multiple materials. Will probably need work.

**Comment by tdw46** [comment]
Testing in Unity VRM Apps I don't see the exact same preview for some of these offsets.... But I do for others.... Needs more investigation.

**Comment by tdw46** [comment]
Okay, now everything is working as expected in unity based apps. Previews in blender match.

**Comment by tdw46** [comment]
Might need some help with the typing here. Will learn from your updates.

**Comment by tdw46** [comment]
Kigu Eye Rig Port to VRM Standard

**Comment by tdw46** [comment]
I've gotten as far as I can with linting @saturday06 I will likely need your help to finish this.

**Comment by saturday06** [comment]
> https://github.com/saturday06/VRM-Addon-for-Blender/pull/552#issuecomment-2312762929
> I think this is good to merge, thanks for your patience! Let me know if there are any parts of the code you'd like formatted differently. I'm trying to learn the best practices you follow.

Your contribution is appreciated.

The repository contains code formatting settings, code type checking settings, and software testing settings.

These are strongly dependent on the tool astral-sh/uv (https://docs.astral.sh/uv/), so you will need to install that first.
Alternatively, you can use Visual Studio Code's devcontainer to set them up automatically.

### To run the code format, follow these steps.

1. install [astral-sh/uv](https://docs.astral.sh/uv/).
2. double-click `tools\format.bat` in the repository to run it.

### To run the code format in Visual Studio Code, follow these steps.

1. install [astral-sh/uv](https://docs.astral.sh/uv/). 
2. in the Visual Studio Code terminal, run the `uv sync` command.
3. run Visual Studio Code's `Format Document`.

The same result can be achieved by using the `Ruff` extension of Visual Studio Code.

### To run the code type check, follow these steps.

1. install [astral-sh/uv](https://docs.astral.sh/uv/).
2. double-click `tools\lint.bat` in the repository and run it.

### To run the type checking of the code in Visual Studio Code, follow these steps.

1. install [astral-sh/uv](https://docs.astral.sh/uv/). 
2. in the Visual Studio Code terminal, run the `uv sync` command.
3. install `Ruff`, `Mypy Type Checker` and `Pylance` extensions in Visual Studio Code.
4. open the py file you want to type check.

### To run the software test of the code, follow these steps.

1. install [astral-sh/uv](https://docs.astral.sh/uv/).
2. in your terminal, run the command `git submodule update --init --recursive`.
3. double-click `tools\test.bat` in the repository and run it.
10. if you get the error `Blender not found`, set the environment variable `BLENDER_VRM_TEST_BLENDER_PATH` to the path of the Blender 4.2 or 3.6 or 3.3 or 2.93 exe file.

### To run the software test of the code in Visual Studio Code, follow these steps.

1. install [astral-sh/uv](https://docs.astral.sh/uv/).
2. in the Visual Studio Code terminal, run the `uv sync` command.
3. in the Visual Studio Code terminal, run the command `git submodule update --init --recursive`.
4. select `Testing` from the left icon in Visual Studio Code
5. select `Configure Python Tests.
6. select `unittests` as the test library.
7. select `Root Directory` as test folder.
8. select `test_*` as test file pattern.
9. press `Run Tests`
10. if you get the error `Blender not found`, set the environment variable `BLENDER_VRM_TEST_BLENDER_PATH` to the path of the Blender 4.2 or 3.6 or 3.3 or 2.93 exe file.

**Comment by saturday06** [comment]
It has been documented: https://vrm-addon-for-blender.info/en/development/

**Comment by tdw46** [comment]
Thanks!!! This helps a lot, I will try this approach and let you know if I have questions~~ 🙌🏻

**Comment by tdw46** [comment]
> It has been documented: https://vrm-addon-for-blender.info/en/development/

I installed astral, ran formatting, type checking, and tests. Looks like all is good locally! Does this look ready to merge to you?

**Comment by saturday06** [comment]
@tdw46 Thanks! I will make some adjustments and merge it.

I am in the process of [changing the license of the source code from MIT to a multi-license that “allows you to choose between MIT or GPL-3.0-or-later”](https://github.com/saturday06/VRM-Addon-for-Blender/issues/548). I need to apply it to the source code of this Pull Request as well, can you please give me permission?

**Comment by tdw46** [comment]
> @tdw46 Thanks! I will make some adjustments and merge it.
> 
> I am in the process of [changing the license of the source code from MIT to a multi-license that “allows you to choose between MIT or GPL-3.0-or-later”](https://github.com/saturday06/VRM-Addon-for-Blender/issues/548). I need to apply it to the source code of this Pull Request as well, can you please give me permission?

I've added you as a collaborator to the repo, so you can make changes as you want before merging any work I submit a pull request for ^_^

I changed the approach slightly here to improve efficiency. I'm now adding nodes to the shader graph procedurally to drive these previews. I mention this because I think you have some material update/refresh code that might fight with this. 

Wanted to make sure you are aware when you are making changes before merge. Thanks!

**Comment by tdw46** [comment]
I noticed an issue with overrides in this new approach using shader graph I need to fix really quick before your merge.

**Comment by tdw46** [comment]
I've noticed another issue with Scaling texturetransform binds on export... UV scaling doesn't match up between blender and VRM apps... Investigating a fix now.

**Comment by tdw46** [comment]
> I've noticed another issue with Scaling texturetransform binds on export... UV scaling doesn't match up between blender and VRM apps... Investigating a fix now.

Alright @saturday06 I've added you as a contributor so you can make changes before merging. And I revised the approach to use shader graph drivers for massive performance boost. That said, I think you'll need to incorporate the material driver group into your scene load material refresh logic. I think that's better left to you.

One lingering thought, I don't have the texture preview nodes arranged cleanly upon adding them. We could consider incorporating the "arrange" operator from this blender extension into the code-base (with credit to the author) to automatically make the graph clean:
[Node Arrange Extension](https://extensions.blender.org/add-ons/node-arrange/?utm_source=blender-4.2.1-lts)

We might also consider warning users that the Texture Transform Bind Y axis scale term requires Y offset in the opposite direction. So, if you scale the texture transform bind Y value to 1.2, you need to make sure your Y offset on that same bind is -0.2, but you don't need to do this for X.

**Comment by saturday06** [comment]
@tdw46  Before merging, the license of the source code for this pull request needs to be changed from MIT to a “choice of MIT or GPL-3.0-or-later” license. Can you please give me your permission?

Because the [Blender Extensions Platform](https://extensions.blender.org/) requires it. I am currently in the process of changing the license of all source code ( https://github.com/saturday06/VRM-Addon-for-Blender/issues/548 )

**Comment by tdw46** [comment]
> @tdw46 Before merging, the license of the source code for this pull request needs to be changed from MIT to a “choice of MIT or GPL-3.0-or-later” license. Can you please give me your permission?
> 
> Because the [Blender Extensions Platform](https://extensions.blender.org/) requires it. I am currently in the process of changing the license of all source code ( #548 )

I invited you to have permission here:
https://github.com/tdw46/VRM-Addon-for-Blender-Beyond/invitations

Is there somewhere else I need to grant you write access?

**Comment by saturday06** [comment]
Thank you. But even if I get repository access, I am not allowed to change the license file of your repository, since the source code in your repository is also under multiple copyright holders.

What I want now is permission to change the license in the future for the source code in this Pull Request.

May I redistribute the source code of this Pull Request as a “choice of MIT or GPL-3.0-or-later” license?

**Comment by tdw46** [comment]
Ahhh I see! Yes, absolutely ^_^

**Comment by saturday06** [comment]
Thank you. Merged!

Essentially, ~~you~~ I will need to ask permission for your old contributions as well. I will contact you again when ready.

**Pull request merged**
