### PR TITLE
Shader group rebuilt to match Unity w/ Sun lamp

### PR DESCRIPTION
**Pull request by aVersionOfReality**
Per our discussion in [the issues thread](https://github.com/saturday06/VRM-Addon-for-Blender/issues/314), I have rebuilt the shader group based on Unity's code. This shader will match Unity when the light settings are correct. They must be:

- Sun Lamp with Strength 1, Color White [1,1,1], Angle 180deg, no Shadows
- World Lighting 0 (can use Lightpath in the World nodes if you still want the background to display color other than black.)

If you use this, I suggest having the addon set the Sun to use these values, and warn users when they don't have them. This setup could be made to work with the sun having Color if the color is input into the nodes.

image

I have not tested this in detail yet and there may still be some issues. We will be testing it more in the coming days.

I am also working on better UVs for the Matcap that will match Unity better and should have that soon.

### CODE REVIEW

**Comment by saturday06** [comment]
Thank you very much. I will check it in my environment this weekend.

**Comment by saturday06** [comment]
@aVersionOfReality Please share me the blend file with the correct setup.

I tried your node but it didn't show the Lit color. I believe that the sun lamp and world light have been set up as specified by you.

- My test .blend file 
https://github.com/saturday06/3d-model-test-resources/blob/unity-mtoon1-debug/blend/render/sphere1.blend

- My reference unity project
https://github.com/saturday06/3d-model-test-resources/tree/unity-mtoon1-debug/unity/UniVrmUrpMtoon1Screenshot

Here is a screenshot of the current situation. Lit Color is not displayed in Blender 3.6.3 and Windows 11
shot

**Comment by saturday06** [comment]
After modifying the Shading Grade nodes, Lit Color now appears. However, the display is different from Unity.

Maybe my settings aren't good enough, so I still want a .blend file that's set up correctly.

スクリーンショット 2023-09-24 173321

**Comment by aVersionOfReality** [comment]
Ah, it is my mistake. I forgot to test without Toon set to 1, and I didn't realize Shading Shift Texture scale defaulted to 1, which I suppose was obvious. Recreating the Unity code snippet is not enough. Many things are different. There must be more happening than is shown in this shader file.

I have a new version where I've fixed both issues, but need to test some other things. Will try to send tomorrow.

**Comment by saturday06** [comment]
Merged. I will make the following changes.

- Use legacy light emulation for a while. I will remove it in the future.
- I will adjust it to work with Blender 2.93 as well.

Any additional changes are welcome.
Thanks!

**Pull request merged**
